#Author: your.email@your.domain.com
#Keywords Summary :
#Feature: List of scenarios.
#Scenario: Business rule through list of steps with arguments.

@tag
Feature: Title of your feature
  I want to use this template for my feature file

  @tag1
  Scenario: Title of your scenario
    Given I want to write a step with precondition
    When I have a Table
    |user1	|123435|
    |user2	|000123|
    |user3	|234354|
    Then I validate the outcomes
    And check more outcomes

 