/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ASUS' at '15/11/18 12:21 AM' with Gradle 2.14.1
 *
 * @author ASUS, @date 15/11/18 12:21 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
