/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ASUS' at '13/11/18 09:06 AM' with Gradle 2.14.1
 *
 * @author ASUS, @date 13/11/18 09:06 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
