/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ASUS' at '8/11/18 11:38 PM' with Gradle 2.14.1
 *
 * @author ASUS, @date 8/11/18 11:38 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
